POST https://api.economapas.com.br/v2/leads/cnpjs/total

###

DELETE  http://localhost:3000/api/services/2



###

GET http://localhost:3000/api/services
Content-Type: application/json
###

POST http://localhost:3000/api/services
Content-Type: application/json

{
  "title": "Manutenção de computadores",
  "subtitle": "Realizo todo o trabalho de manutenção de computares para seu estabelecimento",
  "description": "Trabalho com fardware, resdes , notebooks empressoaras e perifericos",
  "job": "Tecnico de informatica",
  "status": true,
  "views": 5,
  "link": "https://google.com",
  "image": "/images/dev7.svg",
  "icon": "/image/icon.svg",
  "city": "Igrejinha",
  "bairro": "centro",
  "address": "Rua joaquim silva",
  "obs": "Predio segundo piso",
  "number": "12" 
}

###
PATCH http://localhost:3000/api/services/49
Content-Type: application/json

{
  "rate":4
}
