const empresas = [
  //
  {
    CNPJ: "42.167.865/0002-78",
    Razão: "HIDROMAN TERCEIRIZACOES LTDA",
    Fantasia: "",
    Tipo: "AVENIDA",
    Endereço: "ILDO MENEGHETTI",
    Número: 1846,
    Complemento: "",
    Bairro: "CASA DE PEDRA",
    Cidade: "IGREJINHA",
    UF: "RS",
    "cód. IBGE": 4310108,
    CEP: "95.650-000",
    "Telefone 1": 4230285722,
    "Telefone 2": 42999980909,
    "E-mail": "contato@hidroman.com.br",
    Site: "www.hidroman.com.br",
    "CNAE Principal": 3319800,
    "Texto CNAE Principal":
      "Manutenção e reparação de equipamentos e produtos não especificados anteriormente",
    "CNAE Secundário": "1623400,8129000,8299799",
    "Matriz/Filial - Ente Federativo": "Filial",
    "Situação Cad.": "ATIVA",
    "Data Situação Cad.": "12/04/2024",
    "Natureza Jurídica": "Sociedade Empresária Limitada",
    "Data Início Atv.": "12/04/2024",
    "opção pelo MEI": "N",
    "Data entrada MEI": "00/00/0000",
    "Data Exclusão MEI": "00/00/0000",
    "Programas Especiais": "não",
    "Porte Empresa": "EMPRESA DE PEQUENO PORTE",
    "Regime Tributário": "ANO 2021 LUCRO REAL, ANO 2022 LUCRO PRESUMIDO,",
    "Data opção Simples": "01/01/2022",
    "Data Exclusão Simples": "30/11/2022",
    "Capital Social da Empresa": "R$ 100.000,00",
    "Identificador 1° Sócio": "PF-",
    "Nome do Sócio": "KARIN FONTOURA-",
    "Faixa Etária": "31 A 40 ANOS-",
    "CPF/CNPJ do Sócio": "***812920**-",
    Qualificação: "Sócio-ADMINISTRADOR-",
    "Data da Entrada": "//20221122-",
    "Faturamento Estimado": "R$ 360001,00 a R$ 4800000,00",
    "Quadro de Funcionários": "20 A 99 COLABORADORES",
    "Dívidas Federais Ativas": "",
    "Total Dívidas": "R$",
  },
  {
    CNPJ: "54.716.271/0001-77",
    Razão: "D L REPRESENTACOES COMERCIAIS LTDA",
    Fantasia: "D L REPRESENTACOES COMERCIAIS",
    Tipo: "RUA",
    Endereço: "RUI BARBOSA",
    Número: 92,
    Complemento: "",
    Bairro: "FIGUEIRA",
    Cidade: "IGREJINHA",
    UF: "RS",
    "cód. IBGE": 4310108,
    CEP: "95.650-000",
    "Telefone 1": 51983579607,
    "Telefone 2": "000000000000",
    "E-mail": "aline.foesch@gmail.com",
    Site: "",
    "CNAE Principal": 4616800,
    "Texto CNAE Principal":
      "Representantes comerciais e agentes do comércio de téxtil vestuário calçados e artigos de viagem",
    "CNAE Secundário": 4619200,
    "Matriz/Filial - Ente Federativo": "Matriz com 0 Filiais",
    "Situação Cad.": "ATIVA",
    "Data Situação Cad.": "12/04/2024",
    "Natureza Jurídica": "Sociedade Empresária Limitada",
    "Data Início Atv.": "12/04/2024",
    "opção pelo MEI": "",
    "Data entrada MEI": "//",
    "Data Exclusão MEI": "//",
    "Programas Especiais": "não",
    "Porte Empresa": "MICRO EMPRESA",
    "Regime Tributário": "PRESUMIDO OU LUCRO REAL",
    "Data opção Simples": "//",
    "Data Exclusão Simples": "//",
    "Capital Social da Empresa": "R$ 5.000,00",
    "Identificador 1° Sócio": "PF-PF-",
    "Nome do Sócio": "ALINE FOESCH-IGOR GEFERSON HENRICH DA SILVA-",
    "Faixa Etária": "31 A 40 ANOS-31 A 40 ANOS-",
    "CPF/CNPJ do Sócio": "***777420**-***473260**-",
    Qualificação: "Sócio-ADMINISTRADOR-Sócio-ADMINISTRADOR-",
    "Data da Entrada": "//20240412-//20240412-",
    "Faturamento Estimado": "R$ 81001,00 a R$ 3600000,00",
    "Quadro de Funcionários": "3 A 9 COLABORADORES",
    "Dívidas Federais Ativas": "",
    "Total Dívidas": "R$",
  },
  {
    CNPJ: "54.714.244/0001-65",
    Razão: "SERVICOS MEDICOS BRUNO RODRIGUES ALVES LTDA",
    Fantasia: "",
    Tipo: "RUA",
    Endereço: "GETULIO VARGAS",
    Número: 457,
    Complemento: "",
    Bairro: "CENTRO",
    Cidade: "IGREJINHA",
    UF: "RS",
    "cód. IBGE": 4310108,
    CEP: "95.650-000",
    "Telefone 1": 3135667988,
    "Telefone 2": "000000000000",
    "E-mail": "cadastro@agilitconsultoria.com",
    Site: "www.agilitconsultoria.com",
    "CNAE Principal": 8630502,
    "Texto CNAE Principal":
      "Atividade médica ambulatorial com recursos para realização de exames complementares",
    "CNAE Secundário": "",
    "Matriz/Filial - Ente Federativo": "Matriz com 0 Filiais",
    "Situação Cad.": "ATIVA",
    "Data Situação Cad.": "12/04/2024",
    "Natureza Jurídica": "Sociedade Empresária Limitada",
    "Data Início Atv.": "12/04/2024",
    "opção pelo MEI": "",
    "Data entrada MEI": "//",
    "Data Exclusão MEI": "//",
    "Programas Especiais": "não",
    "Porte Empresa": "MICRO EMPRESA",
    "Regime Tributário": "PRESUMIDO OU LUCRO REAL",
    "Data opção Simples": "//",
    "Data Exclusão Simples": "//",
    "Capital Social da Empresa": "R$ 1.000,00",
    "Identificador 1° Sócio": "PF-",
    "Nome do Sócio": "BRUNO RODRIGUES ALVES-",
    "Faixa Etária": "41 A 50 ANOS-",
    "CPF/CNPJ do Sócio": "***087277**-",
    Qualificação: "Sócio-ADMINISTRADOR-",
    "Data da Entrada": "//20240412-",
    "Faturamento Estimado": "R$ 81001,00 a R$ 3600000,00",
    "Quadro de Funcionários": "3 A 9 COLABORADORES",
    "Dívidas Federais Ativas": "",
    "Total Dívidas": "R$",
  },
  {
    CNPJ: "54.701.000/0001-48",
    Razão: "54.701.000 MATEUS BERNARDES DA SILVA",
    Fantasia: "",
    Tipo: "10A RUA",
    Endereço: "ATALIBIO AVELINO SCHILLING",
    Número: 50563,
    Complemento: "",
    Bairro: "MORRO FORTALEZA",
    Cidade: "IGREJINHA",
    UF: "RS",
    "cód. IBGE": 4310108,
    CEP: "95.650-000",
    "Telefone 1": 51995949975,
    "Telefone 2": "",
    "E-mail": "matbernardes2306@gmail.com",
    Site: "",
    "CNAE Principal": 4759899,
    "Texto CNAE Principal":
      "comércio varejista de outros artigos de uso doméstico não especificados anteriormente",
    "CNAE Secundário": "",
    "Matriz/Filial - Ente Federativo": "Matriz com 0 Filiais",
    "Situação Cad.": "ATIVA",
    "Data Situação Cad.": "11/04/2024",
    "Natureza Jurídica": "Empresário (Individual)",
    "Data Início Atv.": "11/04/2024",
    "opção pelo MEI": "S",
    "Data entrada MEI": "11/04/2024",
    "Data Exclusão MEI": "00/00/0000",
    "Programas Especiais": "não",
    "Porte Empresa": "MICRO EMPRESA",
    "Regime Tributário": "SIMPLES NACIONAL",
    "Data opção Simples": "11/04/2024",
    "Data Exclusão Simples": "00/00/0000",
    "Capital Social da Empresa": "R$ 5.000,00",
    "Identificador 1° Sócio": "",
    "Nome do Sócio": "",
    "Faixa Etária": "",
    "CPF/CNPJ do Sócio": "",
    Qualificação: "",
    "Data da Entrada": "",
    "Faturamento Estimado": "R$ 1,00 a R$ 81000,00",
    "Quadro de Funcionários": "1 A 2 COLABORADORES",
    "Dívidas Federais Ativas": "",
    "Total Dívidas": "R$",
  },
  {
    CNPJ: "54.690.828/0001-48",
    Razão: "54.690.828 THIAGO BATISTA DE LIMA",
    Fantasia: "",
    Tipo: "10A RUA",
    Endereço: "RUA OTELO ROSA",
    Número: 76,
    Complemento: "",
    Bairro: "CENTRO",
    Cidade: "IGREJINHA",
    UF: "RS",
    "cód. IBGE": 4310108,
    CEP: "95.650-000",
    "Telefone 1": 51993161143,
    "Telefone 2": "",
    "E-mail": "mkt.thiagolima@gmail.com",
    Site: "",
    "CNAE Principal": 8599699,
    "Texto CNAE Principal":
      "Outras atividades de ensino não especificadas anteriormente",
    "CNAE Secundário": 8592903,
    "Matriz/Filial - Ente Federativo": "Matriz com 0 Filiais",
    "Situação Cad.": "ATIVA",
    "Data Situação Cad.": "11/04/2024",
    "Natureza Jurídica": "Empresário (Individual)",
    "Data Início Atv.": "11/04/2024",
    "opção pelo MEI": "S",
    "Data entrada MEI": "11/04/2024",
    "Data Exclusão MEI": "00/00/0000",
    "Programas Especiais": "não",
    "Porte Empresa": "MICRO EMPRESA",
    "Regime Tributário": "SIMPLES NACIONAL",
    "Data opção Simples": "11/04/2024",
    "Data Exclusão Simples": "00/00/0000",
    "Capital Social da Empresa": "R$ 1.000,00",
    "Identificador 1° Sócio": "",
    "Nome do Sócio": "",
    "Faixa Etária": "",
    "CPF/CNPJ do Sócio": "",
    Qualificação: "",
    "Data da Entrada": "",
    "Faturamento Estimado": "R$ 1,00 a R$ 81000,00",
    "Quadro de Funcionários": "1 A 2 COLABORADORES",
    "Dívidas Federais Ativas": "",
    "Total Dívidas": "R$",
  },
  {
    CNPJ: "54.694.009/0001-79",
    Razão: "54.694.009 LUCAS MERLINI DOS REIS",
    Fantasia: "",
    Tipo: "RUA",
    Endereço: "7 DE JULHO",
    Número: 907,
    Complemento: "SALA 3",
    Bairro: "CENTRO",
    Cidade: "IGREJINHA",
    UF: "RS",
    "cód. IBGE": 4310108,
    CEP: "95.650-000",
    "Telefone 1": 51997441816,
    "Telefone 2": "",
    "E-mail": "merlinilucas87@gmail.com",
    Site: "",
    "CNAE Principal": 9602501,
    "Texto CNAE Principal": "Cabeleireiros manicure e pedicure",
    "CNAE Secundário": "",
    "Matriz/Filial - Ente Federativo": "Matriz com 0 Filiais",
    "Situação Cad.": "ATIVA",
    "Data Situação Cad.": "11/04/2024",
    "Natureza Jurídica": "Empresário (Individual)",
    "Data Início Atv.": "11/04/2024",
    "opção pelo MEI": "S",
    "Data entrada MEI": "11/04/2024",
    "Data Exclusão MEI": "00/00/0000",
    "Programas Especiais": "não",
    "Porte Empresa": "MICRO EMPRESA",
    "Regime Tributário": "SIMPLES NACIONAL",
    "Data opção Simples": "11/04/2024",
    "Data Exclusão Simples": "00/00/0000",
    "Capital Social da Empresa": "R$ 2.000,00",
    "Identificador 1° Sócio": "",
    "Nome do Sócio": "",
    "Faixa Etária": "",
    "CPF/CNPJ do Sócio": "",
    Qualificação: "",
    "Data da Entrada": "",
    "Faturamento Estimado": "R$ 1,00 a R$ 81000,00",
    "Quadro de Funcionários": "1 A 2 COLABORADORES",
    "Dívidas Federais Ativas": "",
    "Total Dívidas": "R$",
  },
  {
    CNPJ: "54.668.158/0001-63",
    Razão: "EMILIO L. SASTRE LTDA",
    Fantasia: "",
    Tipo: "RUA",
    Endereço: "CARLOS GOMES",
    Número: 218,
    Complemento: "",
    Bairro: "BOM PASTOR",
    Cidade: "IGREJINHA",
    UF: "RS",
    "cód. IBGE": 4310108,
    CEP: "95.650-000",
    "Telefone 1": 53999514856,
    "Telefone 2": "000000000000",
    "E-mail": "emiliosastre@gmail.com",
    Site: "",
    "CNAE Principal": 7500100,
    "Texto CNAE Principal": "Atividades veterin�rias",
    "CNAE Secundário": "",
    "Matriz/Filial - Ente Federativo": "Matriz com 0 Filiais",
    "Situação Cad.": "ATIVA",
    "Data Situação Cad.": "10/04/2024",
    "Natureza Jurídica": "Sociedade Empresária Limitada",
    "Data Início Atv.": "10/04/2024",
    "opção pelo MEI": "",
    "Data entrada MEI": "//",
    "Data Exclusão MEI": "//",
    "Programas Especiais": "não",
    "Porte Empresa": "MICRO EMPRESA",
    "Regime Tributário": "PRESUMIDO OU LUCRO REAL",
    "Data opção Simples": "//",
    "Data Exclusão Simples": "//",
    "Capital Social da Empresa": "R$ 5.000,00",
    "Identificador 1° Sócio": "PF-",
    "Nome do Sócio": "EMILIO LEMKE SASTRE-",
    "Faixa Etária": "31 A 40 ANOS-",
    "CPF/CNPJ do Sócio": "***256800**-",
    Qualificação: "Sócio-ADMINISTRADOR-",
    "Data da Entrada": "//20240410-",
    "Faturamento Estimado": "R$ 81001,00 a R$ 3600000,00",
    "Quadro de Funcionários": "3 A 9 COLABORADORES",
    "Dívidas Federais Ativas": "",
    "Total Dívidas": "R$",
  },
  {
    CNPJ: "54.678.744/0001-99",
    Razão: "54.678.744 EDER PAULO FORMIGHIERI",
    Fantasia: "",
    Tipo: "RUA",
    Endereço: "FELIPE LAMB",
    Número: 121,
    Complemento: "",
    Bairro: "FIGUEIRAS",
    Cidade: "IGREJINHA",
    UF: "RS",
    "cód. IBGE": 4310108,
    CEP: "95.650-000",
    "Telefone 1": 51999903621,
    "Telefone 2": "",
    "E-mail": "ederpaulo02@gmail.com",
    Site: "",
    "CNAE Principal": 9609299,
    "Texto CNAE Principal":
      "Outras atividades de servi�os pessoais não especificadas anteriormente",
    "CNAE Secundário": 4322302,
    "Matriz/Filial - Ente Federativo": "Matriz com 0 Filiais",
    "Situação Cad.": "ATIVA",
    "Data Situação Cad.": "10/04/2024",
    "Natureza Jurídica": "Empresário (Individual)",
    "Data Início Atv.": "10/04/2024",
    "opção pelo MEI": "S",
    "Data entrada MEI": "10/04/2024",
    "Data Exclusão MEI": "00/00/0000",
    "Programas Especiais": "não",
    "Porte Empresa": "MICRO EMPRESA",
    "Regime Tributário": "SIMPLES NACIONAL",
    "Data opção Simples": "10/04/2024",
    "Data Exclusão Simples": "00/00/0000",
    "Capital Social da Empresa": "R$ 2.000,00",
    "Identificador 1° Sócio": "",
    "Nome do Sócio": "",
    "Faixa Etária": "",
    "CPF/CNPJ do Sócio": "",
    Qualificação: "",
    "Data da Entrada": "",
    "Faturamento Estimado": "R$ 1,00 a R$ 81000,00",
    "Quadro de Funcionários": "1 A 2 COLABORADORES",
    "Dívidas Federais Ativas": "",
    "Total Dívidas": "R$",
  },
  {
    CNPJ: "54.654.258/0001-30",
    Razão: "54.654.258 HUGO ADALBERTO SANTOS PADILHA",
    Fantasia: "",
    Tipo: "ESTRADA",
    Endereço: "EDGAR WILLY WOLFF",
    Número: 1185,
    Complemento: "",
    Bairro: "SERRA GRANDE",
    Cidade: "IGREJINHA",
    UF: "RS",
    "cód. IBGE": 4310108,
    CEP: "95.650-000",
    "Telefone 1": 51998545152,
    "Telefone 2": "",
    "E-mail": "hugopadilha28@gmail.com",
    Site: "",
    "CNAE Principal": 1531902,
    "Texto CNAE Principal": "Acabamento de calçados de couro sob contrato",
    "CNAE Secundário": "",
    "Matriz/Filial - Ente Federativo": "Matriz com 0 Filiais",
    "Situação Cad.": "ATIVA",
    "Data Situação Cad.": "09/04/2024",
    "Natureza Jurídica": "Empresário (Individual)",
    "Data Início Atv.": "09/04/2024",
    "opção pelo MEI": "S",
    "Data entrada MEI": "09/04/2024",
    "Data Exclusão MEI": "00/00/0000",
    "Programas Especiais": "não",
    "Porte Empresa": "MICRO EMPRESA",
    "Regime Tributário": "SIMPLES NACIONAL",
    "Data opção Simples": "09/04/2024",
    "Data Exclusão Simples": "00/00/0000",
    "Capital Social da Empresa": "R$ 5.000,00",
    "Identificador 1° Sócio": "",
    "Nome do Sócio": "",
    "Faixa Etária": "",
    "CPF/CNPJ do Sócio": "",
    Qualificação: "",
    "Data da Entrada": "",
    "Faturamento Estimado": "R$ 1,00 a R$ 81000,00",
    "Quadro de Funcionários": "1 A 2 COLABORADORES",
    "Dívidas Federais Ativas": "",
    "Total Dívidas": "R$",
  },
  {
    CNPJ: "54.656.992/0001-39",
    Razão: "54.656.992 ERNANI ERNESTO HARTZ",
    Fantasia: "",
    Tipo: "RUA",
    Endereço: "TIRADENTES",
    Número: 37,
    Complemento: "",
    Bairro: "CENTRO",
    Cidade: "IGREJINHA",
    UF: "RS",
    "cód. IBGE": 4310108,
    CEP: "95.650-000",
    "Telefone 1": 51999883398,
    "Telefone 2": "",
    "E-mail": "ernanihartztaxi@gmail.com",
    Site: "",
    "CNAE Principal": 4923001,
    "Texto CNAE Principal": "Servi�o de t�xi",
    "CNAE Secundário": "",
    "Matriz/Filial - Ente Federativo": "Matriz com 0 Filiais",
    "Situação Cad.": "ATIVA",
    "Data Situação Cad.": "09/04/2024",
    "Natureza Jurídica": "Empresário (Individual)",
    "Data Início Atv.": "09/04/2024",
    "opção pelo MEI": "S",
    "Data entrada MEI": "09/04/2024",
    "Data Exclusão MEI": "00/00/0000",
    "Programas Especiais": "não",
    "Porte Empresa": "MICRO EMPRESA",
    "Regime Tributário": "SIMPLES NACIONAL",
    "Data opção Simples": "09/04/2024",
    "Data Exclusão Simples": "00/00/0000",
    "Capital Social da Empresa": "R$ 50.000,00",
    "Identificador 1° Sócio": "",
    "Nome do Sócio": "",
    "Faixa Etária": "",
    "CPF/CNPJ do Sócio": "",
    Qualificação: "",
    "Data da Entrada": "",
    "Faturamento Estimado": "R$ 1,00 a R$ 81000,00",
    "Quadro de Funcionários": "1 A 2 COLABORADORES",
    "Dívidas Federais Ativas": "",
    "Total Dívidas": "R$",
  },
];
